### ISSUE TITLE
Feature request: Preview support for Markdown(MD) files

### ISSUE THREAD

**Issue by charlypa** [aicore/phoenix#140]
Need to know how Markdown file looks after typing in markdown 
* Support GitHub markdown
* Other Martkdowns?

**Comment by TapanManu** [comment]
Github flavoured markdown demo 
after extracting Markdown preview extension for brackets
The following appeared  in the browser (Firefox)
![Screenshot from 2021-11-04 21-22-12](https://user-images.githubusercontent.com/48797926/140373774-d1f04572-43d8-4a83-a208-cdddafef311d.png)

**Comment by TapanManu** [comment]
fixed with https://github.com/aicore/phoenix/issues/223

**Comment by abose** [comment]
Investigate is we can use prose mirror for this:  https://prosemirror.net/examples/markdown/

**Comment by TapanManu** [comment]
#257

**Comment by abose** [comment]
https://github.com/aicore/phoenix/pull/317
Markdown panel basic framework is now live. Closing as done.
