### ISSUE TITLE
Switch language not working

### ISSUE THREAD

**Issue by charlypa** [aicore/phoenix#141]
### Prerequisites

* [ x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Steps to Reproduce

![switch_language](https://user-images.githubusercontent.com/1525027/138421061-007bc1d5-5559-4814-9c48-a3c2c4a1a034.gif)

**Comment by abose** [comment]
Fixed with https://github.com/aicore/phoenix/pull/278
