### ISSUE TITLE
Default projects and open files are lost after reload

### ISSUE THREAD

**Issue by charlypa** [aicore/phoenix#172]
Phoenix should restore the state of the editor while reopening the phoenix later point in time

**Comment by abose** [comment]
The state is now reloaded when phoenix is closed and reloaded or across project switches.

The startup issue is related to chrome security preventing native files open on the first faunch, This will be addressed by project selection issue: https://github.com/aicore/phoenix/issues/132 

Closing as fixed, and the new project workflow is tracked separate already.
