### ISSUE TITLE
Feature request Auto hide  Menus

### ISSUE THREAD

**Issue by charlypa** [aicore/phoenix#204]
Phoenix should have an option to hide menus to increase real estate
![auto_hide_menus](https://user-images.githubusercontent.com/1525027/139588456-ab498533-7a4f-4ac2-9178-4fc9e7f1ff60.gif)

**Comment by abose** [comment]
That will make the UX inconsistent. Vs code used tabs on top semantics, brackets use title bar on top. Both have the same real estate. 
* It will also require more clicks to access edit/other frequently used menus. VSCode is more command-driven using the command palette unline phoenix which is UX-driven.
* The top bar is also used as toolbar for navigation items and extensions assume it is present for its use cases. This will break extensions API too.
* Brackets has a no distractions mode already built-in under `view> no distractions` to increase coding focus.

Closing as the hamburger-based navigation is not good UX for brackets.
